service: proxy-intellect

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  createSampleUser:
    handler: handlers.createUserHandler
  listSampleUser:
    handler: handlers.listUserHandler
  getSampleUser:
    handler: handlers.getUserHandler
  updateSampleUser:
    handler: handlers.updateUserHandler
  deleteSampleUser:
    handler: handlers.deleteUserHandler
  createSampleQuiz:
    handler: handlers.createQuizHandler
  listSampleQuiz:
    handler: handlers.listQuizHandler
  getSampleQuiz:
    handler: handlers.getQuizHandler
  updateSampleQuiz:
    handler: handlers.updateQuizHandler
  deleteSampleQuiz:
    handler: handlers.deleteQuizHandler
  collateSampleQuiz:
    handler: handlers.collateQuizHandler
  evaluateSampleQuiz:
    handler: handlers.evaluateQuizHandler
